# Generated by Django 4.1.6 on 2023-02-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
