# Generated by Django 4.1.3 on 2023-02-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
