# Generated by Django 4.1.3 on 2023-02-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
