# Generated by Django 4.1.3 on 2023-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_history_user_sales_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
