# Generated by Django 5.2.6 on 2025-09-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expiry_date',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='manufacturer_date',
            field=models.CharField(blank=True),
        ),
    ]
