# Generated by Django 5.2.6 on 2025-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_stock_expiry_date_stock_manufacturer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='manufacturer_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
